#!/usr/bin/env bun

import { readdir } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { $ } from 'bun';

// Get project name
const { dirname } = import.meta;
const projectPath = resolve(dirname, '..')
const project = basename(projectPath);

// Create README.md content
const readme = `\
# ${project}

![Bun](https://img.shields.io/badge/Bun-%23000000.svg?style=flat&logo=bun&logoColor=white)
[![Checked with Biome](https://img.shields.io/badge/Checked_with-Biome-60a5fa?style=flat&logo=biome)](https://biomejs.dev)
`;

// Write README.md
const readmeFile = Bun.file(`${projectPath}/README.md`);
await readmeFile.write(readme);

// Remove LICENSE
const licenseFile = Bun.file(`${projectPath}/LICENSE`);
await licenseFile.delete();

// Remove license field from package.json
const packageJson = Bun.file(`${projectPath}/package.json`);
const contents = await packageJson.json();
contents.license = undefined;
await Bun.write(packageJson, `${JSON.stringify(contents, null, 2)}\n`);

// Remove this script
// await $`rm scripts/postinstall`;
const postinstallFile = Bun.file(`${projectPath}/scripts/postinstall`);
await postinstallFile.delete();

// If scripts folder is empty, remove it
const files = await readdir(dirname);
if (!files.length) {
  await $`rmdir scripts`;
}

// Log success
console.log('Postinstall script executed successfully');
